# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='publish_on', verbose_name='title')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(editable=False, verbose_name='updated on')),
                ('publish_on', models.DateTimeField(verbose_name='publish on')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[('1', 'Draft'), ('2', 'Public')], db_index=True, default='1', verbose_name='status')),
                ('comment_status', models.IntegerField(choices=[('0', 'Open'), ('1', 'Closed')], db_index=True, default='0', verbose_name='comment status')),
                ('teaser', models.TextField(blank=True, verbose_name='teaser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
